kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: masters-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: masters-installer
subjects:
- kind: ServiceAccount
  name: masters-installer
  namespace: kube-system
