kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: masters-installer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:     ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs:     ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs:     ["get", "list", "watch"]
#  - apiGroups: ["extensions", "apps"]
#    resources: ["deployments"]
#    verbs:     ["get", "list", "watch", "create", "update", "patch", "delete"]
